export enum PortfolioItem {
  ARCHITECTURE = "architecture",
  DRONE = "drone",
  NATURE = "nature",
  PORTRAIT = "portrait",
}

export const portfolioData = {
  [PortfolioItem.ARCHITECTURE]: [
    "/img/images/architecture/1.jpg",
    "/img/images/architecture/2.jpg",
    "/img/images/architecture/3.jpg",
    "/img/images/architecture/4.jpg",
    "/img/images/architecture/5.jpg",
    "/img/images/architecture/6.jpg",
    "/img/images/architecture/7.jpg",
    "/img/images/architecture/8.jpg",
    "/img/images/architecture/9.jpg",
  ],
  [PortfolioItem.DRONE]: [
    "/img/images/drone/1.jpg",
    "/img/images/drone/2.jpg",
    "/img/images/drone/3.jpg",
    "/img/images/drone/4.jpg",
    "/img/images/drone/5.jpg",
    "/img/images/drone/6.jpg",
    "/img/images/drone/7.jpg",
    "/img/images/drone/8.jpg",
    "/img/images/drone/9.jpg",
    "/img/images/drone/10.jpg",
    "/img/images/drone/11.jpg",
    "/img/images/drone/12.jpg",
    "/img/images/drone/13.jpg",
    "/img/images/drone/14.jpg",
  ],
  [PortfolioItem.NATURE]: [
    "/img/images/nature/1.jpg",
    "/img/images/nature/2.jpg",
    "/img/images/nature/3.jpg",
    "/img/images/nature/4.jpg",
    "/img/images/nature/5.jpg",
    "/img/images/nature/6.jpg",
    "/img/images/nature/7.jpg",
    "/img/images/nature/8.jpg",
    "/img/images/nature/9.jpg",
    "/img/images/nature/10.jpg",
  ],
  [PortfolioItem.PORTRAIT]: [
    "/img/images/portrait/1.jpg",
    "/img/images/portrait/2.jpg",
    "/img/images/portrait/3.jpg",
    "/img/images/portrait/4.jpg",
    "/img/images/portrait/5.jpg",
    "/img/images/portrait/6.jpg",
    "/img/images/portrait/7.jpg",
    "/img/images/portrait/8.jpg",
    "/img/images/portrait/9.jpg",
    "/img/images/portrait/10.jpg",
    "/img/images/portrait/11.jpg",
    "/img/images/portrait/12.jpg",
    "/img/images/portrait/13.jpg",
    "/img/images/portrait/14.jpg",
  ],
};
